#This file created to use for the application that I developed for e-commerece where prodcut-service, order-service, payment-service will utilized from the service-registry
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
